#%RAML 1.0 DataType
displayName: Profile
description: Un profil de dresseur Pokomon
properties:
  _id: string
  username: string
  picture: string
  email: string
  candy:
    type: integer
    description: Le nombre de bonbon en ma posséssion servant à faire évoluer un Pokomon
